## Deliverable 3. Create a Travel Itinerary Map.

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [3]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("vacation_search/WeatherPy_vacation.csv")
vacation_df.head(15)

,City_ID,City,Country,Max Temp,Description,Lat,Lng,Hotel Name
0,0,Kruisfontein,ZA,59.88,moderate rain,-34.0033,24.7314,Oyster Bay House Rental
1,6,Bluff,NZ,60.39,few clouds,-46.6000,168.3333,Bluff Homestead - Guesthouse & Campervan Park
2,9,Bredasdorp,ZA,62.62,overcast clouds,-34.5322,20.0403,Bredasdorp Country Manor
3,12,Lebu,CL,54.64,clear sky,-37.6167,-73.6500,Hostal Las Lilas
4,24,Ponta Delgada,PT,59.72,scattered clouds,37.7333,-25.6667,Vila Nova Hotel
5,26,Haimen,CN,62.49,overcast clouds,23.1935,116.6142,Jinghao Business Hotel
6,32,Hermanus,ZA,58.80,overcast clouds,-34.4187,19.2345,Misty Waves Boutique Hotel
7,34,Presidencia Roque Saenz Pena,AR,57.20,clear sky,-26.7852,-60.4388,Hotel Gualok
8,36,Mount Gambier,AU,64.31,overcast clouds,-37.8333,140.7667,The Commodore
9,41,Salalah,OM,69.89,clear sky,17.0151,54.0924,"HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel"
10,49,Port Alfred,ZA,67.57,moderate rain,-33.5906,26.8910,The Halyards Hotel
11,62,Ribeira Grande,PT,60.66,overcast clouds,38.5167,-28.7000,Quinta da Meia Eira
12,64,San Patricio,US,65.84,clear sky,28.0170,-97.5169,"Motel 6 Sinton, TX"
13,65,Tiznit,MA,52.02,broken clouds,29.5833,-9.5000,NaN
14,67,Castro,BR,64.49,overcast clouds,-24.7911,-50.0119,CHACARA BAILLY

In [4]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Description} and {Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]


# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [5]:
# 4a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [6]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df['City'] == 'Kruisfontein']
vacation_end = vacation_df.loc[vacation_df['City'] == 'Kruisfontein']
vacation_stop1 = vacation_df.loc[vacation_df['City'] == 'Bredasdorp']
vacation_stop2 = vacation_df.loc[vacation_df['City'] == 'Hermanus'] 
vacation_stop3 = vacation_df.loc[vacation_df['City'] == 'Port Alfred']

In [7]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start["Lat"].to_numpy()[0], vacation_start["Lng"].to_numpy()[0]
end = vacation_end["Lat"].to_numpy()[0], vacation_end["Lng"].to_numpy()[0]
stop1 = vacation_stop1["Lat"].to_numpy()[0], vacation_stop1["Lng"].to_numpy()[0]
stop2 = vacation_stop2["Lat"].to_numpy()[0], vacation_stop2["Lng"].to_numpy()[0]
stop3= vacation_stop3["Lat"].to_numpy()[0], vacation_stop3["Lng"].to_numpy()[0]

In [8]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

fig = gmaps.figure()
vacation_driving_trip = gmaps.directions_layer(start, end, waypoints=[stop1, stop2, stop3], travel_mode='DRIVING')
fig.add_layer(vacation_driving_trip)

fig

Figure(layout=FigureLayout(height='420px'))

In [22]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Description,Lat,Lng,Hotel Name
0,0,Kruisfontein,ZA,59.88,moderate rain,-34.0033,24.7314,Oyster Bay House Rental
1,9,Bredasdorp,ZA,62.62,overcast clouds,-34.5322,20.0403,Bredasdorp Country Manor
2,32,Hermanus,ZA,58.80,overcast clouds,-34.4187,19.2345,Misty Waves Boutique Hotel
3,49,Port Alfred,ZA,67.57,moderate rain,-33.5906,26.8910,The Halyards Hotel

In [24]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Description} and {Max Temp} °F</dd>
</d1>
"""
# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [25]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure()
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))